name: haskell.nix CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Weekly to maintain cache

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Setup Nix with Flakes support
      uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Run TUI build script
      run: |
        # Make the TUI script executable
        chmod +x ./tui
        
        # Run the TUI script in non-interactive mode to build all executables
        ./tui --build-all
        
   # - name: Run specific tests
     # run: |
        # Example of running a specific executable with arguments
        # ./result/bin/your-executable your-arguments

    # Optional: Cache Nix store to speed up builds
    - uses: actions/cache@v2
      with:
        path: /nix/store
        key: ${{ runner.os }}-nix-${{ hashFiles('flake.lock') }}
        restore-keys: |
          ${{ runner.os }}-nix-